== Building a multibranch Pipeline project

This repository is for the
https://jenkins.io/doc/tutorials/build-a-multibranch-pipeline-project/[Build
a multibranch Pipeline project] tutorial in the
https://jenkins.io/doc/[Jenkins User Documentation].

This tutorial uses the same application that the
https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/[Build
a Node.js and React app with npm] tutorial is based on. Therefore,
you’ll be building and testing the same application but this time, its
delivery will be different depending on the Git branch that Jenkins
builds from. That is, the branch being built determines which delivery
stage of your Pipeline is executed.

The `jenkins` directory contains an example of the `Jenkinsfile`
(i.e. Pipeline) you’ll be creating yourself during the tutorial and the
`scripts` subdirectory contains shell scripts with commands that are
executed when Jenkins processes either the ``Deliver for development''
or ``Deploy for production'' stages of your Pipeline (depending on the
branch that Jenkins builds from).

== Getting Started with Create React App (https://create-react-app.dev/docs/getting-started/[npx create-react-app tutorial])

This project was bootstrapped with
https://github.com/facebook/create-react-app[Create React App].

=== Available Scripts

In the project directory, you can run:

==== `npm start`

Runs the app in the development mode. +
Open http://localhost:3000 to view it in your browser.

The page will reload when you make changes. +
You may also see any lint errors in the console.

==== `npm test`

Launches the test runner in the interactive watch mode. +
See the section about
https://facebook.github.io/create-react-app/docs/running-tests[running
tests] for more information.

==== `npm run build`

Builds the app for production to the `build` folder. +
It correctly bundles React in production mode and optimizes the build
for the best performance.

The build is minified and the filenames include the hashes. +
Your app is ready to be deployed!

See the section about
https://facebook.github.io/create-react-app/docs/deployment[deployment]
for more information.

==== `npm run eject`

*Note: this is a one-way operation. Once you `eject`, you can’t go
back!*

If you aren’t satisfied with the build tool and configuration choices,
you can `eject` at any time. This command will remove the single build
dependency from your project.

Instead, it will copy all the configuration files and the transitive
dependencies (webpack, Babel, ESLint, etc) right into your project so
you have full control over them. All of the commands except `eject` will
still work, but they will point to the copied scripts so you can tweak
them. At this point you’re on your own.

You don’t have to ever use `eject`. The curated feature set is suitable
for small and middle deployments, and you shouldn’t feel obligated to
use this feature. However we understand that this tool wouldn’t be
useful if you couldn’t customize it when you are ready for it.

=== Learn More

You can learn more in the
https://facebook.github.io/create-react-app/docs/getting-started[Create
React App documentation].

To learn React, check out the https://reactjs.org/[React documentation].

==== Code Splitting

This section has moved here:
https://facebook.github.io/create-react-app/docs/code-splitting

==== Analyzing the Bundle Size

This section has moved here:
https://facebook.github.io/create-react-app/docs/analyzing-the-bundle-size

==== Making a Progressive Web App

This section has moved here:
https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app

==== Advanced Configuration

This section has moved here:
https://facebook.github.io/create-react-app/docs/advanced-configuration

==== Deployment

This section has moved here:
https://facebook.github.io/create-react-app/docs/deployment

==== `npm run build` fails to minify

This section has moved here:
https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify
